### ISSUE TITLE
Why does unpacking a DictEncoding insert a ChainedVector layer?

### ISSUE THREAD

**Issue by msavael** [JuliaData/Arrow.jl#109]
I've got a simple DictEncoding example here:

```
using Arrow
df = (; a=Arrow.DictEncode([1,2,3]),)
Arrow.write("test.arrow", df)
roundtrip = Arrow.Table("test.arrow")
```

And I'm trying to work out why it inserts a ChainedVector on the dictionary "keys":
```
julia> roundtrip.a
3-element Arrow.DictEncoded{Int64,UInt8,SentinelArrays.ChainedVector{Int64,Arrow.Primitive{Int64,Array{Int64,1}}}}:
 1
 2
 3
julia> roundtrip.a.encoding.data.arrays
1-element Array{Arrow.Primitive{Int64,Array{Int64,1}},1}:
 [1, 2, 3]
```

I think this is the code that is doing it:
https://github.com/JuliaData/Arrow.jl/blob/main/src/arraytypes/dictencoding.jl#L160-L166

Is there a particular reason it always ensures the DictEncoding.data is a ChainedVector?

If it's possible to avoid this extra layer of indirection, I think it would be nice. It does have a small overhead, presumably from the `ChainedVector` `searchsorted`:
```
layered = roundtrip.a
delayered = Arrow.DictEncoded(layered.arrow, layered.validity, layered.indices, Arrow.DictEncoding{Float64, Arrow.Primitive{Float64,Array{Float64,1}}}(layered.encoding.id, layered.encoding.data.arrays[1], false, layered.encoding.metadata), layered.metadata)
julia> @benchmark @inbounds getindex($(layered), 10)
BenchmarkTools.Trial: 
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     5.420 ns (0.00% GC)
  median time:      5.434 ns (0.00% GC)
  mean time:        6.628 ns (0.00% GC)
  maximum time:     27.485 ns (0.00% GC)
  --------------
  samples:          10000
  evals/sample:     1000
julia> @benchmark @inbounds getindex($(delayered), 10)
BenchmarkTools.Trial: 
  memory estimate:  0 bytes
  allocs estimate:  0
  --------------
  minimum time:     3.880 ns (0.00% GC)
  median time:      3.886 ns (0.00% GC)
  mean time:        3.918 ns (0.00% GC)
  maximum time:     19.588 ns (0.00% GC)
  --------------
  samples:          10000
  evals/sample:     1000
  ```
  
  Thanks,
  Marcin

**Comment by quinnj** [comment]
Yeah, we could probably avoid ChainedVector since it's probably not often needed. The reason we use it is to support DictEncoded columns that span multiple record batches, where subsequent record batches may add additional elements to the dict encoding. But probably most common is a single dict encoding in the first record batch and nothing additional afterwards. Let me look into it.

**Comment by msavael** [comment]
Makes sense - thanks for looking!

**Comment by quinnj** [comment]
Hmmmm, actually looking at the code, it shouldn't be a ChainedVector _unless_ there are multiple batches. Is that the case for you?

**Comment by quinnj** [comment]
Oh, I see it now in your original example; yeah, something weird is going on here. Let me figure out why the ChainedVector is getting put in there.

**Comment by quinnj** [comment]
Ok, I think I got it figured out. https://github.com/JuliaData/Arrow.jl/pull/110

**Comment by msavael** [comment]
Just tested - looks good, and fixes the real-world case I had. Thank you!
