### ISSUE TITLE
DictEncoded doesn't write as DictEncoded

### ISSUE THREAD

**Issue by dmbates** [JuliaData/Arrow.jl#116]
`Arrow.toarrowvector` of a Arrow.DictEncoded type returns an `Arrow.List`.
```
julia> atbl = Arrow.Table(fnm);

julia> typeof(atbl.a)
Arrow.DictEncoded{String, UInt8, Arrow.List{String, Int32, Vector{UInt8}}}

julia> Arrow.toarrowvector(atbl.a)
6-element Arrow.List{String, Int32, Arrow.ToList{UInt8, true, String, Int32}}:
 "a"
 "a"
 "a"
 "b"
 "b"
 "b"
```
Perhaps it doesn't detect that `Arrow.DictEncoded` is a factor-like (in the R sense) object.

I can look at this if you wish but I'm not entirely sure where

**Comment by quinnj** [comment]
Fixed in #119
