### ISSUE TITLE
Arrow.jl issue with struct types

### ISSUE THREAD

**Issue by atteson** [JuliaData/Arrow.jl#128]
As demonstrated by the following shell scripts, Arrow.jl seems to lose its understanding of a struct type after restarting julia:

```
#!/bin/sh

julia <<EOF
using Arrow

struct T1
x::Int
end

Arrow.write( "test.arrow", (x=T1.(rand(Int, 100)),) );

exit()
EOF

julia <<EOF
using Arrow

struct T1
x::Int
end

Arrow.Table( "test.arrow" );
EOF

rm test.arrow
 
```

**Comment by ericphanson** [comment]
I think this has the same cause as https://github.com/JuliaData/Arrow.jl/issues/88, which is that Arrow sometimes registers types at write time. I think it might be better if it errored instead and asked you to register it manually, so that you knew that was a needed step.

**Comment by atteson** [comment]
Thanks.  I'm new to Arrow and didn't see the bit about registering types.  I'll close the issue.
