### ISSUE TITLE
Better fallback when registered types don't match

### ISSUE THREAD

**Issue by rofinn** [JuliaData/Arrow.jl#133]
Currently, if a registered type changes, the load result will just be `#undef`. It'd be nice if there was a better fallback to a `NamedTuple` if possible?

Example:

Lets say I have a package like this:

```julia
module People

using Arrow

export Person

struct Person
    name::String
end

function __init__()
    Arrow.ArrowTypes.registertype!(Person, Person)
end

end
```

I proceed to save a person column as per the docs:
```julia
using Arrow, People

table = (person=[Person("Alice"), Person("Bob")],)
Arrow.write("people.arrow", table)
```
Now, we later load that file after the `Person` struct has be changed to:
```julia
struct Person
    name::String
    id::Int
end
```
```julia
using Arrow, People

Arrow.Table("test.arrow")
Arrow.Table: (person = Main.People.Person[#undef, #undef],)
```
Ideally, I'd at least get `NamedTuple` types to reconstruct that data as necessary? It's kinda gross, but I guess an alternative would be to version the structs explicitly, such that it's always loadable?

**Comment by quinnj** [comment]
As of v1.3, you can always pass `Arrow.Table(file; convert=false)` to get back the "plain bits" that were serialized, i.e., it will avoid constructing any custom types.

In v1.3, you can also define your own:
```julia
ArrowTypes.fromarrow(::Type{T}, x...) = ...
```
method where `x...` will be the serialized fields in the order they were serialized. This opens up teh possibility of custom types managing their own "migrations" if their internal type changes. In their `fromarrow` method, they would check if the serialized arguments are in the "old order" or the "new order".

Do you think there's more we want to do here? That seems to offer quite a bit of flexibility for those who run into these cases.

**Comment by rofinn** [comment]
> Do you think there's more we want to do here?

Sorry, for the late response. Yep, that looks good, thanks! The new Interval example in the docs helped a lot. I'm also assuming we can define multiple methods for `fromarrow` to basically support all previous positional argument constructors via dispatch?

**Comment by quinnj** [comment]
Yeah, `fromarrow` shoudl provide all the flexibility needed.
