### ISSUE TITLE
Arrow.write("my.arrow", CategoricalArray([1,2,3])) hangs

### ISSUE THREAD

**Issue by jtrakk** [JuliaData/Arrow.jl#143]
`Arrow.write("my.arrow", CategoricalArray([1,2,3]))` hangs.

```
  [69666777] Arrow v1.2.4
  [324d7699] CategoricalArrays v0.9.3
```
julia 1.5

**Comment by quinnj** [comment]
I'm going to see how we can throw a better error here, but `Arrow.write` expects a valid "table" as the 2nd argument (a single "scalar element" AbstractArray is not a table). You probably want something like `Arrow.write("my.arrow", (col1=CategoricalArray([1,2,3]),))`

**Comment by jtrakk** [comment]
Thanks. Any chance of defining an interface so everything would fail that doesn't match `AbstractTable` or something?

**Comment by quinnj** [comment]
Not at the moment; it's a larger language issue as a whole, but there are some ideas floating around.

**Comment by quinnj** [comment]
Ok, I ended up figuring out a better, more general solution here: https://github.com/JuliaData/Arrow.jl/pull/147. i.e. by default, only allow up to 6 levels of nested serialization, which should be a very generous default that no one should really hit. But it's good in that it will automatically trip in cases where people pass recursive data structures, like CategoricalPool.
