### ISSUE TITLE
Usage with MPI

### ISSUE THREAD

**Issue by calebwin** [JuliaData/Arrow.jl#151]
Would it be possible to use an Arrow table with MPI communication primitives? Could we use MPI broadcasting for example to move an Arrow table around processes?

**Comment by quinnj** [comment]
Theoretically....yes? I'm not very familiar with MPI or how it communicates things between processes. But essentially you can always do `Arrow.Table(::Vector{UInt8})` where the byte vector points to valid arrow memory. So if you were to `Arrow.write("data.arrow", ...)` some data, then you could do `Arrow.Table("data.arrow")` from multiple processes and they'll all point to the same mmapped arrow data, for one example. If MPI has a way to move a blob of bytes between processes, then this should be possible. One example of doing this in memory would be something like:
```julia
io = IOBuffer()
Arrow.write(io, data)
seekstart(io)
MPI.sendbytes(another_process, read(io))
# from other process
received_bytes = MPI.receivebytes(other_process)
tbl = Arrow.Table(received_bytes)
```

**Comment by calebwin** [comment]
Thanks for your reponse!

MPI does let you communicate bytes between processes so I actually think something like your example would work.

> ```julia
> io = IOBuffer()
> Arrow.write(io, data)
> seekstart(io)
> ```

This would not be zero-copy, right?

> ```julia
> tbl = Arrow.Table(received_bytes)
> ```

But would this be?

I'm thinking about how distributed shuffles could be implemented with MPI + Arrow and trying to understand if performance would be comparable to implementation using other Arrow-based work like [Ballista](https://ballistacompute.org/) and Arrow IPC.

**Comment by quinnj** [comment]
When you do `Arrow.write(::IOBuffer, ...)`, it's writing the arrow data in the IPC format into the IOBuffer, which will grow it's internal `Vector{UInt8}` in order to fit the data. To then avoid an additional copy, we could do `view(io.data, 1:io.ptr-1))` to send the bytes to another process. You're correct that `Arrow.Table(received_bytes)` is zero-copy; the returned `Arrow.Table` object is just a "view" into the input byte vector interpreting the data.

I'm not familiar with what "distributed shuffles" means.

**Comment by calebwin** [comment]
Thanks for your help.

By distributed shuffle, I mean doing doing an all-to-all communication like what is required for hash joins for example.

It seems like implementing a shuffle should be possible using MPI.jl and Arrow.jl. MPI.jl provides an [`Alltoallv!`](https://juliaparallel.github.io/MPI.jl/latest/collective/#MPI.Alltoallv!) for communicating `Array{UInt8}`s (they also support communicating `Ptr`s or `Ref`s interestingly...). These buffers can be converted to and from `Arrow.Table`s using `Arrow.write` and `Arrow.Table` constructor. And the actual splitting/concatenating of tables (for example for a hash join) can be done through the `DataFrame` interface.

The only part I'm unsure about is whether I should be communicating `Array{Uint8}`s or `Ptr`s..

**Comment by quinnj** [comment]
Yeah, it'd be worth looking into what actually gets passed around; if they have a way of safely sharing `Ptr`s between processes, then that's probably pretty efficient as opposed to sending entire `Vector{UInt8}` over the wire. Going to close for now as I don't think there's anything to be done in Arrow.jl; but feel free to comment if you run into any issues or if you think there's something that coudl be easier here.

**Comment by calebwin** [comment]
Thanks for your help here! I'll let you know how it goes.
