### ISSUE TITLE
Do we need to handle data compression yet?

### ISSUE THREAD

**Issue by quinnj** [JuliaData/Arrow.jl#16]

**Comment by dmbates** [comment]
I suppose this is obvious but it would be more of a priority to handle data compression in `Arrow.Table`, in case other systems wrote a compressed file, than in `Arrow.write`.

**Comment by quinnj** [comment]
Relevant part of the spec: https://github.com/apache/arrow/blob/master/format/Message.fbs#L45

**Comment by quinnj** [comment]
done in https://github.com/JuliaData/Arrow.jl/pull/26
