### ISSUE TITLE
TimeZones.jl support

### ISSUE THREAD

**Issue by oxinabox** [JuliaData/Arrow.jl#17]
From what i gather the C bindings for Array used DateTimes with timezones.

It would be very useful to support TimeZones.jl for that.

**Comment by quinnj** [comment]
Yeah, we definitely should. If someone wants to take a stab at this, we'd want to change https://github.com/JuliaData/Arrow.jl/blob/ad50006ad8f387887892d7922e3863cbc6db8335/src/eltypes.jl#L227 to use `ZonedDateTime`, then add write support by adding a `toarrow` definition for `ZonedDateTime` around here: https://github.com/JuliaData/Arrow.jl/blob/ad50006ad8f387887892d7922e3863cbc6db8335/src/write.jl#L219.

**Comment by quinnj** [comment]
Implemented in #50
