### ISSUE TITLE
Arrow.DictEncoded conversion in, e.g. DataFrame

### ISSUE THREAD

**Issue by dmbates** [JuliaData/Arrow.jl#19]
I'm not sure if this is an `Arrow` issue, or a `Tables` issue, or a `DataFrames` issue but when I converted an Arrow.Table for which the columntable type is
```
::NamedTuple{(:Subj, :CC, :trial, :Q, :F, :P, :Pword, :Item, :rt, :Score), Tuple{Arrow.DictEncoded{String, UInt8}, Arrow.DictEncoded{String, UInt8}, Arrow.Primitive{Int16, Int16}, Arrow.DictEncoded{String, UInt8}, Arrow.DictEncoded{String, UInt8}, Arrow.DictEncoded{String, UInt8}, Arrow.DictEncoded{String, UInt16}, Arrow.DictEncoded{String, UInt16}, Arrow.Primitive{Int16, Int16}, Arrow.DictEncoded{String, UInt8}}}
```
all of my compact representations as `Arrow.DictEncoded{String, UInt8}` were converted to `Vector{String}`, which, in these cases, inflates the amount of storage used considerably.  Of course, I can go back and convert them to `PooledArrays` but it seems that somewhere along the line one of the packages should recognize that an `Arrow.DictEncoded{String, UInt8}` is best converted to a `PooledVector{String, UInt8, Vector{UInt8}}`

**Comment by bkamins** [comment]
I would add dependency on PooledArrays.jl as it is lightweight and do as @dmbates suggests. Then, in particular this benefits DataFrames.jl which has a fast path for `PooledVector`.

**Comment by quinnj** [comment]
Hmmm, yes, we should have better `copy` definitions for Arrow column types. But we should also wrap `Arrow.Table` in `Tables.CopiedColumns` so DataFrames doesn't make a copy by default; the point of Arrow.jl is to very efficiently load data and be able to do DataFrames stuff on them, so we want to ensure the default avoids the copying. We should also highlight in the README/docs that the arrow format is very much immutable; you can run great analytics/queries over the data, but for mutating, it's an explicit step to convert away from the arrow formatted columns.

**Comment by bkamins** [comment]
> We should have better copy definitions for Arrow column types

agreed

> But we should also wrap Arrow.Table in Tables.CopiedColumns so DataFrames doesn't make a copy by default

This would be OK given the objective of the package, but as you note - we then should be very clear that this is the case. Note that in old CSV.jl 90% of issues/questions raised in DataFrames.jl were about immutability of returned columns (in the time they were immutable). And we then should add an instruction how to perform a copy somewhere in the docs.

**Comment by quinnj** [comment]
Ok, fix is up: https://github.com/JuliaData/Arrow.jl/pull/21
