### ISSUE TITLE
Automated conversion fails for `Date{MILLISECOND, Int64}`

### ISSUE THREAD

**Issue by piever** [JuliaData/Arrow.jl#206]
Reposting from slack.

Automated conversion fails for `Date{MILLISECOND, Int64}`. It infers that the type is `DateTime`, but then errors when attempting to convert. Using `convert=false` and manually converting later works.

MWE:

```julia
julia> using Arrow, Dates

julia> table = Arrow.Table("faulty_date.arrow");

julia> table.date[1]
ERROR: MethodError: no method matching Int64(::Arrow.Date{Arrow.Flatbuf.DateUnitModule.MILLISECOND, Int64})
Closest candidates are:
  (::Type{T})(::AbstractChar) where T<:Union{AbstractChar, Number} at char.jl:50
  (::Type{T})(::BigInt) where T<:Union{Int128, Int16, Int32, Int64, Int8} at gmp.jl:356
  (::Type{T})(::Base.TwicePrecision) where T<:Number at twiceprecision.jl:243
  ...
Stacktrace:
 [1] DateTime(y::Arrow.Date{Arrow.Flatbuf.DateUnitModule.MILLISECOND, Int64}, m::Int64, d::Int64, h::Int64, mi::Int64, s::Int64, ms::Int64, ampm::Dates.AMPM) (repeats 2 times)
   @ Dates C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\Dates\src\types.jl:383
 [2] fromarrow(#unused#::Type{DateTime}, x::Arrow.Date{Arrow.Flatbuf.DateUnitModule.MILLISECOND, Int64})
   @ Arrow.ArrowTypes ~\.julia\packages\Arrow\ggVa0\src\ArrowTypes\src\ArrowTypes.jl:157
 [3] getindex(p::Arrow.Primitive{DateTime, Vector{Arrow.Date{Arrow.Flatbuf.DateUnitModule.MILLISECOND, Int64}}}, i::Int64)
   @ Arrow ~\.julia\packages\Arrow\ggVa0\src\arraytypes\primitive.jl:48
 [4] top-level scope
   @ REPL[13]:1

julia> raw_table = Arrow.Table("faulty_date.arrow", convert=false);

julia> convert(DateTime, raw_table.date[1])
2019-01-01T00:00:00
```

I suspect the problem is that the type `DateTime` is correctly inferred, but then Arrow calls the constructor instead of the conversion, but only the conversion is defined.

I'm sharing the file (sorry it's zipped but github would not let me upload otherwise).

[faulty_date.zip](https://github.com/JuliaData/Arrow.jl/files/6562480/faulty_date.zip)

**Comment by piever** [comment]
Thanks for merging the PR! Would it be possible to tag a patch release with the fix?

**Comment by jrevels** [comment]
@piever Ah, I tagged a minor release (1.5) that included the fix yesterday, would that suffice? Otherwise could cut a v1.4 release branch and tag v1.4.1 from there

**Comment by piever** [comment]
Thanks for the release! I've updated to Arrow 1.5 and everything works smoothly, as far as I'm concerned there's no need for backporting.
