### ISSUE TITLE
Stable docs point towards an old version

### ISSUE THREAD

**Issue by KristofferC** [JuliaData/Arrow.jl#249]
https://arrow.juliadata.org/stable/ gives you the docs for v1.0.1. The latest version is 2.1.0.

**Comment by ericphanson** [comment]
I think TagBot needs a deploy key so it can push the tag with more privileges and so trigger workflows.

no deploy key: https://github.com/JuliaData/Arrow.jl/blob/main/.github/workflows/TagBot.yml

need for deploy key: https://github.com/JuliaRegistries/TagBot#ssh-deploy-keys
