### ISSUE TITLE
Support for Decimal

### ISSUE THREAD

**Issue by jtrakk** [JuliaData/Arrow.jl#264]
Arrow [supports Decimal types](https://arrow.apache.org/docs/cpp/api/datatype.html). When trying to serialize Decimals.Decimal I get 

```jl
MethodError: no method matching write(::IOBuffer, ::Decimals.Decimal)
```

I'm not sure what I should do here. Is this something that Arrow.jl should support or should I register my own handler? I'm not sure how to specify that I want to use the Arrow-native decimal type.

**Comment by quinnj** [comment]
I think the best solution would be for the Decimals.jl package to take a dependency on the lightweight ArrowTypes.jl package (which lives in this repo, but is registered separately), and where it can declare the appropriate `ArrowKind`/`ArrowType` overloads (as described in the docs [here](https://arrow.juliadata.org/stable/manual/#Custom-types))
