### ISSUE TITLE
Inconsistent Bool vectors from Julia to Python via Arrow

### ISSUE THREAD

**Issue by FuZhiyu** [JuliaData/Arrow.jl#38]
Just try to bring awareness to this issue but please feel free to close it if it is me that misused the API (but still worthwhile to keep a record of the "correct usage" though).

In Julia: 
```
using DataFrames, Arrow, Random
Random.seed!(1)
test = DataFrame(a = randn(10000))
test.a = test.a .> 0.5
Arrow.write("test.arrow", test)
test = Arrow.Table("test.arrow") |> DataFrame
@show sum(test.a)
```
which gives 3133.

Then I load the same file from python using pyarrow:

```
import pyarrow.feather as feather
import pandas as pd
dt = feather.read_feather("test.arrow")
dt.sum()
```
which gives 384. By eye browsing the vector in Python is very inconsistent with the one saved in Julia.

Version info:
Julia:
```
Julia Version 1.5.0
Commit 96786e2 (2020-08-01 23:44 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E7-8891 v2 @ 3.20GHz
  WORD_SIZE: 64
  LIBM: libimf
  LLVM: libLLVM-9.0.1 (ORCJIT, ivybridge)
```
Arrow.jl is 0.3.0.

Python is on 3.8.2 with Pyarrow 1.0.1.

Thanks!

**Comment by quinnj** [comment]
Yeah, this is a bug; I forgot that `Bool` columns are treated specially and are bitpacked in the format; and it's lame that no where in the formal specification do they clarify or explain this, but it was the same with the feather format.

**Comment by quinnj** [comment]
Thanks again for reporting; I believe https://github.com/JuliaData/Arrow.jl/pull/40 should fix this
