### ISSUE TITLE
Does Arrow.jl Support Handling for Larger-Than-Memory Conditions?

### ISSUE THREAD

**Issue by TheCedarPrince** [JuliaData/Arrow.jl#45]
Many thanks to @quinnj and the rest of the JuliaData group for making this wonderful package!

I have been exploring Arrow.jl and the Apache Arrow standards and was wondering if Arrow.jl was able to support handling for Larger-Than-Memory conditions? I was exploring `mmap` based off of the email chain here as I conversed with members from the Apache Arrow community: https://lists.apache.org/thread.html/rd4a366fbb7104e306e342bd41a18f8ff24bdfc6151906270920999b6%40%3Cuser.arrow.apache.org%3E

I noticed that the fundamental `Arrow.Table` function utilizes memory mapping so my question can be distilled to, "Does Arrow.jl handle memory mapping for me so I don't have to worry about Larger-Than-Memory conditions?"

**Comment by quinnj** [comment]
Answer posted! https://lists.apache.org/thread.html/r94f1dc7727c94639faaf34c73edbfeb3d40356abc384934c27d1e774%40%3Cuser.arrow.apache.org%3E
