### ISSUE TITLE
In-memory zero copy support

### ISSUE THREAD

**Issue by roland-hochmuth** [JuliaData/Arrow.jl#51]
I'm very excited to see support for Arrow in Julia! I was interested in seeing how Julia's Arrow performance compared to Python's based on the blog at, https://towardsdatascience.com/apache-arrow-read-dataframe-with-zero-memory-69634092b1a. The performance is much slower, at least on the first iteration through the data. After analyzing performance and looking at the implementation a bit, it looks like the Julia implementation is copying the dataset into memory even though the file is memory-mapped. The memory allocations is high and matches the amount of memory in the dataset.

I understand that support for Arrow in Julia is new, but I was wondering if my understanding is correct and if you are planning to be able to iterate over columns in a memory-mapped Arrow file without having to copy the entire dataset into memory first. 

Regards --Roland

**Comment by quinnj** [comment]
Can you share

**Comment by quinnj** [comment]
Can you share the output of your Julia session? There shouldn't be any copying going on, so if there is, that would be a bug and it'd be nice to track it down. Do note that with Julia, the 1st time calling a function (`Arrow.write` or `Arrow.Table`), the function is JIT compiled, and so a slowdown is expected. Subsequent calls to the same function will be much faster (since the cached compiled code is reused).

**Comment by roland-hochmuth** [comment]
Great to know that this is unexpected.

Here is a link to the Palmer Penguins Dataset in Arrow format, https://1drv.ms/u/s!AoS_W6B7iNaNkP4AAEIJy_LCLZHCAg?e=Smhyh0. The dataset was created using the Jupyter program referenced in the article above at, https://gist.github.com/simicd/f0e8fcd277bb3fa932369551b97d5b07 from the original csv dataset. The zip is ~50 MB. Uncompressed it is ~200 MB.

The program is as follows:

`using Arrow, Mmap

filename = "penguin-dataset-nonan.arrow"

@time t = Arrow.Table(filename)`

The output is as follows:

`Starting Julia...
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.5.2 (2020-09-23)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |
1.671394 seconds (5.32 M allocations: 268.759 MiB, 4.96% gc time)`

The second time I run the program the output is as follows:

` 0.000586 seconds (1.01 k allocations: 64.844 KiB)`

Please let me know if you need any other info. If this is just the overhead of the JIT, which would explain why the second run is so fast, that would be awesome.

Regards --Roland

**Comment by roland-hochmuth** [comment]
I've done a bit more analysis and I've convinced myself that this is just due to the overhead of the JIT. Sorry about flagging this as an issue. 

On the positive side, after the first iteration, the performance of Julia Arrow on the above dataset is much better than the Python Arrow implementation.

I'm going to close this issue out.
