### ISSUE TITLE
Arrow conversion type for naive Julia DateTime - Arrow.Date or Arrow.Timestamp?

### ISSUE THREAD

**Issue by msavael** [JuliaData/Arrow.jl#58]
I was surprised that a `DateTime` gets automatically converted to an Arrow `Date` with MILLISECOND units. Could it be more natural to convert it to an Arrow `Timestamp` with no timezone info, as documented here: https://github.com/apache/arrow/blob/master/format/Schema.fbs#L234-L238

This seems to be what `pyarrow` does by default.

I'm not quite clear on why Date MILLISECOND (https://github.com/apache/arrow/blob/master/format/Schema.fbs#L196-L204) exists at all - it seems to overlap with Timestamp. Perhaps you know better?

**Comment by quinnj** [comment]
Yeah, I think this is a bug; I meant to change it to Timestamp when we started supporting ZonedDateTime, but forgot to. PR up: https://github.com/JuliaData/Arrow.jl/pull/66

**Comment by msavael** [comment]
Greeat, thanks for fixing!
