### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by ExpandingMan** [JuliaData/Arrow.jl#7]
We should have full-blown Documenter.jl documentation.  I will help, I just wanted to open this issue to track.

Anyway, thanks so much for taking this whole thing over!  I must admit I feel a pang of regret for not carrying it all the way through myself, especially when I was so close, but as I was doing on it entirely in my free time, and the feared nightmares in which it would be absolutely crucial for me to have a full robust arrow package in order to even use Julia at work never materialized, it was incredibly hard for me to stay motivated, especially when I hit major obstacles (like the flatbuffers issues).  Let this be a lesson not to take on major projects during playtime that are frankly just no goddamn fun 😆

**Comment by quinnj** [comment]
Done in #54
