### ISSUE TITLE
is not a valid arrow file

### ISSUE THREAD

**Issue by jangorecki** [JuliaData/Arrow.jl#71]
When attempting to read arrow file but having a typo in the file name, the error message could mention that file doesn't exists rather than saying it is not a valid file.

**Comment by quinnj** [comment]
I mean........there's not really a way for Arrow to know if you're "close" to a valid file or if the file actually doesn't exist? Saying it doesn't exist is still accurate, even if you mistype it.

**Comment by jangorecki** [comment]
So why then it doesn't say that file doesn't exist?

**Comment by jangorecki** [comment]
```julia
x = Arrow.Table("dir/non-existing_file.feather")
#ERROR: ArgumentError: dir/non-existing_file.feather is not a valid arrow file
#Stacktrace:
# [1] #Table#84 at /home/jan/.julia/packages/Arrow/Gl8iW/src/table.jl:179 [inlined]
# [2] Table at /home/jan/.julia/packages/Arrow/Gl8iW/src/table.jl:179 [inlined] (repeats 2 times)
# [3] top-level scope at REPL[9]:1
```

**Comment by quinnj** [comment]
Ah, my bad; I was confused and thought we already said it didn't exist. Will change.

**Comment by quinnj** [comment]
Updated the error message: https://github.com/JuliaData/Arrow.jl/commit/9f805ba6fc8126364efb492a29010a353b005fb6
