### ISSUE TITLE
factor read as string

### ISSUE THREAD

**Issue by jangorecki** [JuliaData/Arrow.jl#72]
Having a feather v2 file saved from R where some fields are of factor type. When importing in R or python I am getting those fields as factor/category, as expected. In julia they are read as string. I would like to read them as categorical variables instead.

**Comment by quinnj** [comment]
Arrow.jl reads these kinds of "encoded" columns as `Arrow.DictEncoded`; which is an efficient encoding of the categorical values. It maps directly from the file, so no copying is done, which maximizes read performance.

If you call `copy(col)` on one of these categorical columns, you'll get a `PooledArray`, which is a similar representation. If you'd like to get a CategoricalArray specifically, you can just call `categorical(col)` after having done `using CategoricalArrays` and I think that should work and be very efficient (@nalimilan can confirm?).

Ah, one thing I forgot is that currently `Arrow.DictEncoded` doesn't implement the `DataAPI.refarray` overloads, which can lead to some optimizations in the DataFrames grouping code, for example. I'll put that as a TODO item.

**Comment by nalimilan** [comment]
Yes conversion to `CategoricalArray` should be fast once you implement `refarray` and `refpool`.

**Comment by jangorecki** [comment]
Thank you for explanation. In case if I want to operate on native JuliaDF memory layout data frame, do I have to call `copy` on a data frame?
```julia
df = copy(DataFrame(Arrow.Table(file)))
```
If so, then IMO worth to add that to documentation.

**Comment by bkamins** [comment]
Yes - you need to copy, see e.g. https://bkamins.github.io/julialang/2020/11/06/arrow.html.

It is also described in the DataFrames.jl Tutorial in this notebook: https://github.com/bkamins/Julia-DataFrames-Tutorial/blob/master/04_loadsave.ipynb
