### ISSUE TITLE
why not clean memory ,is it an Arrow's feature,not a bug?

### ISSUE THREAD

**Issue by jesseventura** [JuliaData/Arrow.jl#80]
I've posted this when i use python's pandas to read parquet using pyarrow engine, it makes memory leaking problem.
https://issues.apache.org/jira/browse/ARROW-6874?focusedCommentId=17171226&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-17171226

when i use Arrow.jl to read feather, also has the same problem.
code is here:

@showprogress 1 "reading market data" for fp in glob("*.feather","/mnt/Data/market_data/")[1:4]
    println(fp)
    open(fp) do h
        tab = Arrow.Table(read(h))
        df = DataFrame(tab)
        finalize(tab)
        tab = nothing
        GC.gc()
    end

and mem grows .....
maybe the same  problem but different causes....

**Comment by quinnj** [comment]
In the case of Arrow.jl here, when you do `df = DataFrame(tab)`, the underlying arrow file is not freed, because the columns are re-used from `Arrow.Table` to `DataFrame`. If you want to make a copy of the columns, you can do `df = DataFrame(tab; copycols=true)`.

**Comment by jesseventura** [comment]
> In the case of Arrow.jl here, when you do `df = DataFrame(tab)`, the underlying arrow file is not freed, because the columns are re-used from `Arrow.Table` to `DataFrame`. If you want to make a copy of the columns, you can do `df = DataFrame(tab; copycols=true)`.

Thanks a lot， so that is what  'zero-copy' means ~~~

**Comment by jesseventura** [comment]
I found only when i have a compressed arrow format(lz4 or zstd) , the memory leak problem ocurres.

**Comment by jesseventura** [comment]
> In the case of Arrow.jl here, when you do `df = DataFrame(tab)`, the underlying arrow file is not freed, because the columns are re-used from `Arrow.Table` to `DataFrame`. If you want to make a copy of the columns, you can do `df = DataFrame(tab; copycols=true)`.

in CodecLz4 frame_compression.jl implements initialize and finalize…

 """
    TranscodingStreams.finalize(codec::LZ4FrameDecompressor)

Finalizes the LZ4F Decompression Codec.
 """
function TranscodingStreams.finalize(codec::LZ4FrameDecompressor)::Nothing
    LZ4F_freeDecompressionContext(codec.dctx[])
    nothing
end

```
"""
Releases the memory of a `LZ4F_cctx`.
"""
function LZ4F_freeCompressionContext(cctx::Ptr{LZ4F_cctx})
    ccall((:LZ4F_freeCompressionContext, liblz4), Csize_t, (Ptr{LZ4F_cctx},), cctx)
end

```

i'm not sure Ref objects would execute the finalize segment, since it's calling a 3rd-party c library function.
