### ISSUE TITLE
Error with DatePart('Z')

### ISSUE THREAD

**Issue by Felix-Gauthier** [JuliaData/Arrow.jl#81]
Hello, I have encountered an small problem if one of my `dateformat`s after adding `Arrow` to the environment.

<details>
<summary>MWE</summary>

```julia
julia> using Dates

julia> time_str = "2020-12-17T20:11:39.093Z"
"2020-12-17T20:11:39.093Z"

julia> DateTime(time_str, dateformat"yyyy-mm-ddTHH:MM:SS.sZ")
2020-12-17T20:11:39.093

julia> using Arrow

julia> DateTime(time_str, dateformat"yyyy-mm-ddTHH:MM:SS.sZ")
ERROR: ArgumentError: Unable to parse date time. Expected directive DatePart(Z) at char 22
```

</details>

On julia `v1.5.3` and `Arrow#v1.0.3`

It's not a big deal though, since I can just remove the 'Z' char and it works fine but I feel it could be worth looking into.

Thank you

**Comment by Felix-Gauthier** [comment]
I'd like to point out that in my case, it was very easy to figure out the issue came from type piracy in `Arrow.jl` but in different circumstances the reason might not be so obvious

**Comment by quinnj** [comment]
The piracy isnt' in Arrow.jl itself, but the TimeZones.jl package we use. @omus @oxinabox

**Comment by oxinabox** [comment]
Do open an issue on TimeZones.jl.
Though it begs the question: why are using a `Z` specifier if your data doesn't have the `Z` (timezone) field?
Seems like your dateformat doesn't actually agree with your data; and it was working before by coincidence.

**Comment by omus** [comment]
You're running into: https://github.com/JuliaTime/TimeZones.jl/issues/303. If you escape `Z` in your `dateformat` (e.g. `dateformat"yyyy-mm-ddTHH:MM:SS.s\Z"`) you won't see this issue anymore

**Comment by Felix-Gauthier** [comment]
I've corrected the `dateformat` string to avoid this issue in the future, thank you to everyone for your valuable input.
