### ISSUE TITLE
memory not freed reading python exported compressed feather format 

### ISSUE THREAD

**Issue by jesseventura** [JuliaData/Arrow.jl#93]
first of all, greate thanks to the authors and contributers.
I'm looking for fast data load/save solutions between python and julia for a long time,  and now i've got rid of csv and database format.
i've tried a lot,but  finally i choose feather/arrow. it's now the fastest format for me.

here comes the issue and reproducible codes:

### here is python code creating several feather files....

```
import numpy as np
from pyarrow.feather import write_feather
import os

for i in range(5):
    for comp_type in ['lz4','zstd']:
        fout = 'pydata.{}.feather.{}'.format(i+1,comp_type)
        if os.path.isfile(fout):
            continue
        write_feather(pd.DataFrame(pd.np.random.rand(100000,1000)), fout, compression=comp_type)
```

# and here is repeatly

```
using Arrow
using DataFrames

@showprogress 1 "read repeatly" for ii in range(1,10)
    i = mod(ii,5)+1
    @time df = copy(DataFrame(Arrow.Table("pydata.$i.feather.zstd"), copycols=true))
    finalize(df)
    sleep(1)
end
```

## and here is the mem size  ,nearly up to 16G

| PID     |  VSZ       |        RSS    |
| ---- | ---- | ---- |
|55623  | 19133564 | 17207488   |

**Comment by quinnj** [comment]
Sorry for the slow response here; I tried the code out on the latest Arrow.jl and DataFrames.jl#main and the memory seems to stay steady while reading. Can you maybe try again using the latest Arrow release and DataFrames#main to see if you can reproduce? If so, can you detail a little more what platform you're on and how you're monitoring the memory? Just want to make sure I understand exactly what you're seeing.

**Comment by jesseventura** [comment]
YES!!! AND MANY Thanks.
when I upgrade from 1.3.0 to latest version, this error's GONE.Memory stays steady around 6G.
Maybe some dependencies are fixed. Here is my upgrading process.

![截图_2021-04-25_10-48-06](https://user-images.githubusercontent.com/7834861/115978702-f3074100-a5b3-11eb-99cb-ed7e93c03dc0.png)
