### ISSUE TITLE
Arrow.write slow perf with ZonedDateTime

### ISSUE THREAD

**Issue by juliengooris** [JuliaData/Arrow.jl#95]
I'm trying to serialize a DataFrame with multiple columns types, including a ZonedDateTime column, with Arrow.jl. It appears ZonedDateTime columns have (or seem to have) a huge impact on the Arrow.write performance as compared to simple DateTime. Any diagnostic of that issue or potential remedy ?

```
using DataFrames, Dates, TimeZones, Arrow, BenchmarkTools

# Create a test dataframe
df_length = Int(1e3)
df = DataFrame(
    int = rand(0:1000, long_test_df_length),
    int_missing = rand(vcat(collect(0:10), [missing]), long_test_df_length),
    cont = randn(long_test_df_length),
    cont_missing = rand(vcat(randn(10), [missing]), long_test_df_length),
    str = rand(["a", "b", "c", "d"], long_test_df_length),
    str_missing = rand(["a", "b", "c", "d", missing], long_test_df_length),
)

# DF to Arrow in buffer function 
serialize(df::DataFrames.AbstractDataFrame) = Arrow.write(IOBuffer(), df)

# Add regular DateTime column to df
df_with_dt = copy(df)
insertcols!(df_with_dt, "date" => collect(DateTime(2020, 1, 1 , 0, 0, 0):Second(1):(DateTime(2020, 1, 1, 0, 0, 0) + Second(df_length- 1))))
# Add ZonedDateTime column to df
df_with_zdt = copy(df)
insertcols!(df_with_zdt, "date" => collect(ZonedDateTime(2020, 1, 1 , 0, 0, 0, tz"Europe/Paris"):Second(1):(ZonedDateTime(2020, 1, 1, 0, 0, 0, tz"Europe/Paris") + Second(df_length- 1))))

# Benchmark it
# Regular DateTime
@btime serialize(df_with_dt)    # => 311.645 μs
# ZonedDateTime
@btime serialize(df_with_zdt)    # ==> 1.480 s
```

**Comment by quinnj** [comment]
Hi @juliengooris, sorry for the slow reply here. I'm not seeing the same slow down in my setup:
```julia
julia> # Benchmark it
       # Regular DateTime
       @btime serialize(df_with_dt)    # => 311.645 μs
  276.730 μs (1367 allocations: 172.89 KiB)
IOBuffer(data=UInt8[...], readable=true, writable=true, seekable=true, append=false, size=51144, maxsize=Inf, ptr=51145, mark=-1)

julia> # ZonedDateTime
       @btime serialize(df_with_zdt)    # ==> 1.480 s\
  283.974 μs (1370 allocations: 171.41 KiB)
IOBuffer(data=UInt8[...], readable=true, writable=true, seekable=true, append=false, size=51176, maxsize=Inf, ptr=51177, mark=-1)
```

I'm on OSX, v"1.6.0-beta1" Julia. Can you share your OS and Julia version?

**Comment by juliengooris** [comment]
Hi,

I ran it on : Julia Version 1.4.2 (2020-05-23)
and Ubuntu 18.04.5 LTS.

_____________

Julien Gooris
Tel:  +33 (0)7.81.80.56.83

juliengooris@gmail.com
P *before printing this email, think about the environment*


Le mar. 26 janv. 2021 à 06:40, Jacob Quinn <notifications@github.com> a
écrit :

**Comment by quinnj** [comment]
I'm not sure there's much we can do here unless we get a `ZonedDateTime` type that has the timezone has a type parameter, which would allow avoiding the slightly costly conversion routine. The problem is we first need to scan the `Vector{ZonedDateTime}` to ensure each element has the same timezone, since the arrow format encodes the timezone as the arrow equivalent of a type parameter. Someone proposed an idea of providing an `Arrow.ToTimestamp(x, timezone)` method that would allow a much more efficient encoding. I might try that out real quick and see if it provides a decent work-around.

**Comment by quinnj** [comment]
Ok, `Arrow.ToTimestamp` was pretty easy, so I've made a PR for that: https://github.com/JuliaData/Arrow.jl/pull/173. I get the same timing encoding `ZonedDateTime` as `DateTime` using it:
```julia
julia> @btime serialize(df_with_zdt)    # ==> 1.480 s
  245.639 μs (1356 allocations: 170.98 KiB)
IOBuffer(data=UInt8[...], readable=true, writable=true, seekable=true, append=false, size=51160, maxsize=Inf, ptr=51161, mark=-1)
```
